### ISSUE TITLE
Failed to resolve: com.github.bijoysingh.floating-bubble:2.0.0:

### ISSUE THREAD

**Issue by tharukaCodeWorks** [BijoySingh/FloatingBubbleLib#1]
When i add dependency it will not synced the project with library. How to resolve this.

**Comment by nowshad-hasan** [comment]
Same problem here. In case you ignored - compile 'com.github.bijoysingh.floating-bubble:1.2.0' for Android Support v26.
But I tried both with v26 and v27, but the problem still exists. If you find any solution, please let me know.

**Comment by harmskhosa** [comment]
@tharukateachmeit I'm looking to make use of this library. Is there a reason you closed this issue? Did you solve the problem you were facing?

**Comment by RamiJ3mli** [comment]
The documentation has a dot before "floating_bubble". Change it to a colon instead. 
` implementation "com.github.bijoysingh:floating-bubble:2.0.0"`
